---
# tasks file for os_branding
- name: Uploading custom files
  copy:
    src: "{{item.value.src}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{horizon_custom_uploads}}"
  when: horizon_custom_uploads is defined

- name: Replace cloud name
  lineinfile:
    dest: "{{horizon_settings_path}}local_settings.py"
    regexp: "^SITE_BRANDING"
    line: "SITE_BRANDING = '{{horizon_site_name}}'"
  notify:
    - restart horizon
